# Generated by Django 5.2 on 2025-04-24 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turpiaui', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='touristpoint',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
    ]
