# Generated by Django 5.2 on 2025-04-30 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turpiaui', '0002_touristpoint_is_favorite'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
            ],
        ),
    ]
